# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CourseDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CourseDialog(object):
    def setupUi(self, CourseDialog):
        CourseDialog.setObjectName("CourseDialog")
        CourseDialog.resize(400, 150)
        self.verticalLayoutWidget = QtWidgets.QWidget(CourseDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 381, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.CourseTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.CourseTextEdit.setPlainText("")
        self.CourseTextEdit.setOverwriteMode(False)
        self.CourseTextEdit.setPlaceholderText("")
        self.CourseTextEdit.setObjectName("CourseTextEdit")
        self.verticalLayout.addWidget(self.CourseTextEdit)
        self.Button_save2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_save2.setObjectName("Button_save2")
        self.verticalLayout.addWidget(self.Button_save2)

        self.retranslateUi(CourseDialog)
        QtCore.QMetaObject.connectSlotsByName(CourseDialog)

    def retranslateUi(self, CourseDialog):
        _translate = QtCore.QCoreApplication.translate
        CourseDialog.setWindowTitle(_translate("CourseDialog", "请输入课程名称"))
        self.label.setText(_translate("CourseDialog", "提示：每个课程名称需单独占一行"))
        self.Button_save2.setText(_translate("CourseDialog", "保存"))
