# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(400, 150)
        self.gridLayoutWidget = QtWidgets.QWidget(LoginDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 9, 381, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_uid = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_uid.sizePolicy().hasHeightForWidth())
        self.lineEdit_uid.setSizePolicy(sizePolicy)
        self.lineEdit_uid.setObjectName("lineEdit_uid")
        self.gridLayout.addWidget(self.lineEdit_uid, 0, 1, 1, 1)
        self.Button_save = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_save.sizePolicy().hasHeightForWidth())
        self.Button_save.setSizePolicy(sizePolicy)
        self.Button_save.setObjectName("Button_save")
        self.gridLayout.addWidget(self.Button_save, 2, 1, 1, 1)
        self.label_uid = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_uid.setObjectName("label_uid")
        self.gridLayout.addWidget(self.label_uid, 0, 0, 1, 1)
        self.label_pwd = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_pwd.setObjectName("label_pwd")
        self.gridLayout.addWidget(self.label_pwd, 1, 0, 1, 1)
        self.lineEdit_pwd = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.gridLayout.addWidget(self.lineEdit_pwd, 1, 1, 1, 1)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "请输入登录信息"))
        self.Button_save.setText(_translate("LoginDialog", "保存"))
        self.label_uid.setText(_translate("LoginDialog", "学号："))
        self.label_pwd.setText(_translate("LoginDialog", "密码："))
